microservice-chart:
  namespace: "mdc"
  nameOverride: ""
  fullnameOverride: ""

  # Formula: preStop(15s) + SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE(35s) + buffer(10s) = 60s
  terminationGracePeriodSeconds: 60

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  lifecycle:
    preStop:
      create: true
      command:
        - sleep
        - "15"

  startupProbe:
    create: true
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 10
    failureThreshold: 24
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
    terminationGracePeriodSeconds: 60

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 0
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
    terminationGracePeriodSeconds: 30

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 0
    failureThreshold: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3

  deployment:
    create: true
    topologySpreadConstraints:
      create: true
      useDefaultConfiguration: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /emdtpp(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080
    # proxyBodySize: 2m
    annotations: {
      nginx.ingress.kubernetes.io/satisfy: "any"
    }

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  externalConfigMapValues:
    mdc-common:
      TZ: TZ

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json

  envSecret:
    MONGODB_URI: mongodb-connection-string
    REDIS_CONNECTION_HOSTNAME: emd-redis-primary-connection-hostname
    REDIS_CONNECTION_PASSWORD: emd-redis-primary-access-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  tolerations:
    - key: "mdcOnly"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - mdc
